/** @externs */
/** @suppress {duplicate,checkTypes,externsValidation,uselessCode} */

/** Namespace global cuando se usa como script. */
/** @const */
var inspiretree = inspiretree || {};
/** @const */
inspiretree.dom = inspiretree.dom || {};

/** Formas CommonJS (declaraciones, sin asignaciones). */
/** @const {!Object} */ var module;
/** @type {*} */ module.exports;
/** @const {!Object} */ var exports;

/** Alias que Closure usa tras reescritura CJS (declaración únicamente). */
/** @const */ var module$exports$inspiretree;

/**
 * @externs
 * @suppress {checkTypes,const,duplicate,missingOverride}
 */
// NOTE: generated by tsickle, do not edit.
// Generated from: inspire-tree-dom.d.ts

/**
 * @record
 * @struct
 */
inspiretree.dom.DropTargetValidator = function() {};

/* TODO: CallSignature: inspiretree$dom */
/**
 * @record
 * @struct
 */
inspiretree.dom.Config = function() {};
/** @type {boolean} */
inspiretree.dom.Config.prototype.autoLoadMore;
/** @type {boolean} */
inspiretree.dom.Config.prototype.deferredRendering;
/** @type {{enabled: boolean, validateOn: string, validate: !inspiretree.dom.DropTargetValidator}} */
inspiretree.dom.Config.prototype.dragAndDrop;
/** @type {number} */
inspiretree.dom.Config.prototype.nodeHeight;
/** @type {boolean} */
inspiretree.dom.Config.prototype.showCheckboxes;
/** @type {?|undefined} */
inspiretree.dom.Config.prototype.dragTargets;
/** @type {number} */
inspiretree.dom.Config.prototype.tabindex;
/** @type {*} */
inspiretree.dom.Config.prototype.target;

/**
 * @constructor
 * @struct
 * @public
 * @param {*} tree
 * @param {!inspiretree.dom.Config} opts
 */
inspiretree.dom.InspireTreeDOM = function(tree, opts) {};


/** @suppress {duplicate} */
var module$exports$inspiretree = inspiretree;
